### PR TITLE
support for name_columns_by_row for iget_records

### PR DESCRIPTION
**Pull request by fuhrysteve**

### CODE REVIEW

**Comment by fuhrysteve** [comment]
Need to get tests running locally to get this working right, but looks like it's pretty close

**Comment by chfw** [comment]
You could try start_row=2, which would skip first two rows.

**Comment by chfw** [comment]
Here is the recently(<2wks) updated documentation on [iget_records()](http://pyexcel.readthedocs.io/en/latest/generated/pyexcel.iget_records.html#pyexcel.iget_records).

**Comment by fuhrysteve** [comment]
Interesting - I was probably looking at an older version of the docs.

Does `start_row` behave different, in practice, than `name_columns_by_row`? When I looked at `iget_records` vs `get_records` I immediately assumed this was the same pattern as the whole `items()` vs `iteritems()` in py2.

When I noticed `name_columns_by_row` had no effect with `iget_records`, I assumed it was simply unimplemented functionality.

What I'm getting at is this: would simply setting `start_row = keywords.get('start_row', keywords.get('name_columns_by_row'))` make `list(iget_records())` functionally equivalent to `get_records()`?

It seems to me in a perfect world, `get_records` would look like this and would basically be a convenience / lazy method:

```python
def get_records(self, **keywords):
    return list(self.iget_records(**keywords))
```

**Comment by chfw** [comment]
Start_row would skip the number of the rows while data is being read. Name_columns_by_row in get_records chooses the specified row for headers, but first row is the defaut value. and it can be any row in the data sheet.

In iget_records, it returns a generator, so it is impossble to put nth row as the header unless we buffer the data till the specified now, name_columns_by_row.

Without considering name_columns_by_row parameter, get_records could be regarded in the same way as you described.

**Comment by fuhrysteve** [comment]
That makes complete sense, and now that I've been playing around with it today I understand the functionality better. Thanks!

**Pull request closed without merging**
